### ISSUE TITLE
комментарии по 6 лабе

### ISSUE THREAD

**Issue by Godofnothing** [egorkaGubarev/infa_2020_egorkaGubarev#3]
В целом отпад) С удовольствием залип, добавление звука и ракеты, как расширение проекта всегда хорошо). 
Единственное, на что хотел бы обратить внимание в `set_leaderboard` - если изначально файл `leaderbord.txt` не существует, высветится ошибка. И желательно предусмотреть данную ситуацию либо в коде, либо в репозитории сделать пустой файл изначально. Также полезно использовать менеджеры контекста `with open f as ...`.

**Comment by FrCln** [comment]
Сохраняйте, пожалуйста, нормальные питоновские файлы. Я не хочу запускать jupyter notebook только для того, чтобы посмотреть, что у вас там написано. Ведь это же несложно - скопировать весь этот текст и вставить в обычный текстовый файл с расширением .py.

**Comment by FrCln** [comment]
Если уж лень делать это вручную, вот код, который сделает это автоматически:
```python
import json
nb = json.load(open('catch_the_ball.ipynb'))
text = ''.join((''.join(line for line in cell["source"]) for cell in nb["cells"]))
with open('out.py', 'w') as file:
    file.write(text)
```

**Comment by FrCln** [comment]
Для корректного открытия файла для сохранения очков:
```python
try:
    with open('leaderboard.txt', 'r', encoding='utf-8') as output:
        for line in output:
            line = line.strip()
            leader_list.append(line)
except FileNotFoundError:
    pass
```
Да, при работе с файлами, в которых могут быть русские буквы, нужно указывать кодировку, иначе могут быть проблемы.

**Comment by FrCln** [comment]
Еще хорошо бы предусмотреть возможность выхода из игры каким-то более разумным способом, чем ее убийством средствами ОС (в полноэкранном режиме нет крестика у окошка). Например, по нажатию ESC.
